version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.sql
    ports:
      - "3306:3306"

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - mysql
